[databases]
# Connects to the internal Docker service name of the DB
scrupeak = host=postgis_db port=5432 dbname=scrupeak

[pgbouncer]
listen_port = 6432
listen_addr = *
auth_type = plain
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = transaction

# High-concurrency tuning
max_client_conn = 10000
default_pool_size = 100
min_pool_size = 20
reserve_pool_size = 10
reserve_pool_timeout = 5
server_idle_timeout = 60
log_connections = 0