"""
Global constants for the ScruPeak Spatial Service.
"""

# ID Generation
PARCEL_CODE_RANDOM_PART_MIN = 1000
PARCEL_CODE_RANDOM_PART_MAX = 9999
GRID_ID_FORMAT_LEN = 5
SEQUENCE_FORMAT_LEN = 5

# Spatial
MIN_PARCEL_AREA_SQM = 1.0
SUBDIVISION_AREA_TOLERANCE_PCT = 1.0